# Generated by Django 5.0.6 on 2024-08-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translator', '0004_translation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='correct_file_path',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='incorrect_file_path',
        ),
        migrations.AddField(
            model_name='translation',
            name='iscorrect',
            field=models.BooleanField(default=True),
        ),
    ]
